<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;

class Destination extends Model
{
    use HasFactory, SoftDeletes;

    protected $table = 'destinations';

    protected $fillable = [
        'tenant_id',
        'slug',
        'destination_name',
        'description',
        'region',
        'province',
        'district',
        'best_time_to_visit',
        'nearby_attractions',
        'latitude',
        'longitude',
        'image_url',
        'featured',
        'status',
    ];

    protected $casts = [
        'latitude' => 'decimal:8',
        'longitude' => 'decimal:8',
        'featured' => 'boolean',
    ];

    public static function defaultSeedRows(): array
    {
        return [
            [
                'slug' => 'sigiriya',
                'destination_name' => 'Sigiriya',
                'description' => "A signature heritage stop in Sri Lanka's Cultural Triangle, known for the lion rock fortress, village life, and safari access.",
                'region' => 'Cultural Triangle',
                'province' => 'Central Province',
                'district' => 'Matale',
                'best_time_to_visit' => 'May to September',
                'nearby_attractions' => 'Pidurangala Rock, Dambulla Cave Temple, Minneriya National Park',
                'latitude' => 7.9570,
                'longitude' => 80.7603,
                'image_url' => null,
                'featured' => true,
                'status' => 'active',
            ],
            [
                'slug' => 'dambulla',
                'destination_name' => 'Dambulla',
                'description' => 'A practical base for the Cultural Triangle with cave temples, markets, and easy road links to the north central plains.',
                'region' => 'Cultural Triangle',
                'province' => 'Central Province',
                'district' => 'Matale',
                'best_time_to_visit' => 'May to September',
                'nearby_attractions' => 'Golden Temple, Dambulla Cave Temple, Ibbankatuwa Wetland',
                'latitude' => 7.8570,
                'longitude' => 80.6518,
                'image_url' => null,
                'featured' => false,
                'status' => 'active',
            ],
            [
                'slug' => 'kandy',
                'destination_name' => 'Kandy',
                'description' => "Sri Lanka's hill capital with temple heritage, lake walks, and access to tea-country day trips.",
                'region' => 'Hill Country',
                'province' => 'Central Province',
                'district' => 'Kandy',
                'best_time_to_visit' => 'December to April',
                'nearby_attractions' => 'Temple of the Tooth, Kandy Lake, Royal Botanic Gardens Peradeniya',
                'latitude' => 7.2906,
                'longitude' => 80.6337,
                'image_url' => null,
                'featured' => true,
                'status' => 'active',
            ],
            [
                'slug' => 'nuwara-eliya',
                'destination_name' => 'Nuwara Eliya',
                'description' => 'Cool-climate tea country with colonial architecture, lakeside scenery, and garden estates.',
                'region' => 'Tea Country',
                'province' => 'Central Province',
                'district' => 'Nuwara Eliya',
                'best_time_to_visit' => 'February to April',
                'nearby_attractions' => 'Gregory Lake, Hakgala Botanical Garden, Horton Plains',
                'latitude' => 6.9497,
                'longitude' => 80.7891,
                'image_url' => null,
                'featured' => true,
                'status' => 'active',
            ],
            [
                'slug' => 'ella',
                'destination_name' => 'Ella',
                'description' => 'A relaxed hill-country stop with rail scenery, viewpoints, and easy access to waterfalls and tea estates.',
                'region' => 'Hill Country',
                'province' => 'Uva Province',
                'district' => 'Badulla',
                'best_time_to_visit' => 'December to March',
                'nearby_attractions' => "Nine Arches Bridge, Little Adam's Peak, Ravana Falls",
                'latitude' => 6.8667,
                'longitude' => 81.0466,
                'image_url' => null,
                'featured' => true,
                'status' => 'active',
            ],
            [
                'slug' => 'haputale',
                'destination_name' => 'Haputale',
                'description' => 'A misty ridge town for tea estate views, quiet stays, and long-distance hill scenery.',
                'region' => 'Tea Country',
                'province' => 'Uva Province',
                'district' => 'Badulla',
                'best_time_to_visit' => 'January to April',
                'nearby_attractions' => "Lipton's Seat, Adisham Bungalow, Diyaluma Falls",
                'latitude' => 6.7657,
                'longitude' => 80.9518,
                'image_url' => null,
                'featured' => false,
                'status' => 'active',
            ],
            [
                'slug' => 'anuradhapura',
                'destination_name' => 'Anuradhapura',
                'description' => 'An ancient capital with sacred stupas, archaeology sites, and bike-friendly heritage routes.',
                'region' => 'Cultural Triangle',
                'province' => 'North Central Province',
                'district' => 'Anuradhapura',
                'best_time_to_visit' => 'May to September',
                'nearby_attractions' => 'Sri Maha Bodhi, Ruwanwelisaya, Jetavanaramaya',
                'latitude' => 8.3114,
                'longitude' => 80.4037,
                'image_url' => null,
                'featured' => true,
                'status' => 'active',
            ],
            [
                'slug' => 'polonnaruwa',
                'destination_name' => 'Polonnaruwa',
                'description' => 'A compact heritage city with well-preserved ruins, lakes, and bicycle tours through the old kingdom.',
                'region' => 'Cultural Triangle',
                'province' => 'North Central Province',
                'district' => 'Polonnaruwa',
                'best_time_to_visit' => 'May to September',
                'nearby_attractions' => 'Gal Vihara, Parakrama Samudra, Royal Palace complex',
                'latitude' => 7.9394,
                'longitude' => 81.0021,
                'image_url' => null,
                'featured' => false,
                'status' => 'active',
            ],
            [
                'slug' => 'yala',
                'destination_name' => 'Yala',
                'description' => "Sri Lanka's best known wildlife area for leopard sightings, safaris, and dry-zone landscapes.",
                'region' => 'Wildlife',
                'province' => 'Southern Province',
                'district' => 'Hambantota',
                'best_time_to_visit' => 'February to July',
                'nearby_attractions' => 'Yala National Park, Kataragama, Sithulpawwa',
                'latitude' => 6.3667,
                'longitude' => 81.5170,
                'image_url' => null,
                'featured' => true,
                'status' => 'active',
            ],
            [
                'slug' => 'mirissa',
                'destination_name' => 'Mirissa',
                'description' => 'A south coast beach destination for whale watching, surf breaks, seafood dining, and easy-going stays.',
                'region' => 'South Coast',
                'province' => 'Southern Province',
                'district' => 'Matara',
                'best_time_to_visit' => 'November to April',
                'nearby_attractions' => 'Whale watching, Coconut Tree Hill, Weligama Bay',
                'latitude' => 5.9485,
                'longitude' => 80.4599,
                'image_url' => null,
                'featured' => false,
                'status' => 'active',
            ],
            [
                'slug' => 'galle',
                'destination_name' => 'Galle',
                'description' => 'A historic port city with the Dutch fort, boutique stays, and a walkable old-town waterfront.',
                'region' => 'South Coast',
                'province' => 'Southern Province',
                'district' => 'Galle',
                'best_time_to_visit' => 'November to April',
                'nearby_attractions' => 'Galle Fort, Maritime Museum, Unawatuna beach',
                'latitude' => 6.0535,
                'longitude' => 80.2210,
                'image_url' => null,
                'featured' => true,
                'status' => 'active',
            ],
            [
                'slug' => 'unawatuna',
                'destination_name' => 'Unawatuna',
                'description' => 'A compact beach area with swimming coves, cafes, and fast access to Galle Fort.',
                'region' => 'South Coast',
                'province' => 'Southern Province',
                'district' => 'Galle',
                'best_time_to_visit' => 'November to April',
                'nearby_attractions' => 'Jungle Beach, Japanese Peace Pagoda, Galle Fort',
                'latitude' => 6.0000,
                'longitude' => 80.2500,
                'image_url' => null,
                'featured' => false,
                'status' => 'active',
            ],
            [
                'slug' => 'hikkaduwa',
                'destination_name' => 'Hikkaduwa',
                'description' => 'A lively beach town with snorkeling, coral reefs, and simple coastal accommodation.',
                'region' => 'South Coast',
                'province' => 'Southern Province',
                'district' => 'Galle',
                'best_time_to_visit' => 'November to April',
                'nearby_attractions' => 'Coral Sanctuary, Seenigama Temple, turtle hatcheries',
                'latitude' => 6.1400,
                'longitude' => 80.1000,
                'image_url' => null,
                'featured' => false,
                'status' => 'active',
            ],
            [
                'slug' => 'bentota',
                'destination_name' => 'Bentota',
                'description' => 'A polished resort strip with river cruises, water sports, and calm beach access.',
                'region' => 'West Coast',
                'province' => 'Western Province',
                'district' => 'Kalutara',
                'best_time_to_visit' => 'November to April',
                'nearby_attractions' => 'Bentota River, Lunuganga Estate, turtle conservation centers',
                'latitude' => 6.4269,
                'longitude' => 79.9730,
                'image_url' => null,
                'featured' => true,
                'status' => 'active',
            ],
            [
                'slug' => 'kalpitiya',
                'destination_name' => 'Kalpitiya',
                'description' => 'A lagoon-and-reef peninsula known for kitesurfing, dolphin trips, and relaxed coastal stays.',
                'region' => 'North-West Coast',
                'province' => 'North Western Province',
                'district' => 'Puttalam',
                'best_time_to_visit' => 'May to September',
                'nearby_attractions' => 'Kalpitiya Dutch Fort, Bar Reef, Wilpattu excursions',
                'latitude' => 8.2321,
                'longitude' => 79.7561,
                'image_url' => null,
                'featured' => false,
                'status' => 'active',
            ],
            [
                'slug' => 'trincomalee',
                'destination_name' => 'Trincomalee',
                'description' => 'An east coast harbor city with long beaches, deep-water bays, and temple heritage.',
                'region' => 'East Coast',
                'province' => 'Eastern Province',
                'district' => 'Trincomalee',
                'best_time_to_visit' => 'May to September',
                'nearby_attractions' => 'Koneswaram Temple, Nilaveli, Pigeon Island',
                'latitude' => 8.5874,
                'longitude' => 81.2152,
                'image_url' => null,
                'featured' => true,
                'status' => 'active',
            ],
            [
                'slug' => 'pasikudah',
                'destination_name' => 'Pasikudah',
                'description' => 'A shallow-water beach destination ideal for family stays, lagoon views, and relaxed coastal travel.',
                'region' => 'East Coast',
                'province' => 'Eastern Province',
                'district' => 'Batticaloa',
                'best_time_to_visit' => 'May to September',
                'nearby_attractions' => 'Pasikudah Bay, Kalkudah Beach, Batticaloa lagoon',
                'latitude' => 7.9236,
                'longitude' => 81.5600,
                'image_url' => null,
                'featured' => false,
                'status' => 'active',
            ],
            [
                'slug' => 'arugam-bay',
                'destination_name' => 'Arugam Bay',
                'description' => "Sri Lanka's most famous surf village with a laid-back beach strip and seasonal wave culture.",
                'region' => 'East Coast',
                'province' => 'Eastern Province',
                'district' => 'Ampara',
                'best_time_to_visit' => 'April to October',
                'nearby_attractions' => 'Main Point surf break, Pottuvil Lagoon, Kumana National Park',
                'latitude' => 6.8393,
                'longitude' => 81.8348,
                'image_url' => null,
                'featured' => true,
                'status' => 'active',
            ],
            [
                'slug' => 'jaffna',
                'destination_name' => 'Jaffna',
                'description' => 'A northern cultural hub with island temples, heritage forts, and a distinct Tamil food scene.',
                'region' => 'Northern Peninsula',
                'province' => 'Northern Province',
                'district' => 'Jaffna',
                'best_time_to_visit' => 'May to September',
                'nearby_attractions' => 'Nallur Kandaswamy Temple, Jaffna Fort, Casuarina Beach',
                'latitude' => 9.6615,
                'longitude' => 80.0255,
                'image_url' => null,
                'featured' => true,
                'status' => 'active',
            ],
            [
                'slug' => 'udawalawe',
                'destination_name' => 'Udawalawe',
                'description' => 'A classic safari stop with elephants, reservoir scenery, and easy access from the south and hill country.',
                'region' => 'Wildlife',
                'province' => 'Sabaragamuwa Province',
                'district' => 'Ratnapura',
                'best_time_to_visit' => 'December to April',
                'nearby_attractions' => 'Udawalawe National Park, elephant transit home, Walawe reservoir',
                'latitude' => 6.4330,
                'longitude' => 80.9050,
                'image_url' => null,
                'featured' => false,
                'status' => 'active',
            ],
            [
                'slug' => 'negombo',
                'destination_name' => 'Negombo',
                'description' => 'A convenient arrival city with canal boat rides, seafood restaurants, and easy airport access.',
                'region' => 'West Coast',
                'province' => 'Western Province',
                'district' => 'Gampaha',
                'best_time_to_visit' => 'November to April',
                'nearby_attractions' => "Negombo Lagoon, Dutch Canal, St. Mary's Church",
                'latitude' => 7.2083,
                'longitude' => 79.8358,
                'image_url' => null,
                'featured' => false,
                'status' => 'active',
            ],
            [
                'slug' => 'matara',
                'destination_name' => 'Matara',
                'description' => 'A south coast city with fort heritage, beaches, and access to nearby coastal towns.',
                'region' => 'South Coast',
                'province' => 'Southern Province',
                'district' => 'Matara',
                'best_time_to_visit' => 'November to April',
                'nearby_attractions' => 'Matara Fort, Polhena Beach, Parey Dewa',
                'latitude' => 5.9549,
                'longitude' => 80.5550,
                'image_url' => null,
                'featured' => false,
                'status' => 'active',
            ],
        ];
    }

    public static function normalizeSlug(?string $value, int|string|null $fallback = null): string
    {
        $slug = Str::slug((string) $value);

        if ($slug !== '') {
            return $slug;
        }

        return 'destination-' . ($fallback ?? Str::random(6));
    }

    public function toTourismArray(): array
    {
        $imageUrl = trim((string) ($this->image_url ?? ''));

        return [
            'id' => $this->id,
            'slug' => $this->slug,
            'title' => $this->destination_name,
            'destinationName' => $this->destination_name,
            'destination_name' => $this->destination_name,
            'subtitle' => $this->region ?: $this->province ?: $this->district,
            'description' => $this->description,
            'status' => $this->status,
            'featured' => (bool) $this->featured,
            'image' => $imageUrl ?: null,
            'imageUrl' => $imageUrl ?: null,
            'image_url' => $imageUrl ?: null,
            'href' => '/destinations/' . $this->slug,
            'region' => $this->region,
            'province' => $this->province,
            'district' => $this->district,
            'bestTimeToVisit' => $this->best_time_to_visit,
            'best_time_to_visit' => $this->best_time_to_visit,
            'nearbyAttractions' => $this->nearby_attractions,
            'nearby_attractions' => $this->nearby_attractions,
            'latitude' => $this->latitude !== null ? (float) $this->latitude : null,
            'longitude' => $this->longitude !== null ? (float) $this->longitude : null,
            'created_at' => $this->created_at,
            'updated_at' => $this->updated_at,
        ];
    }
}
